create table HOUSE (
  HOUSE_ID INT,
  HOUSE_NAME VARCHAR(100) not NULL
);

create table HOUSEWORK (
  HOUSEWORK_ID INT,
  HOUSEWORD_NAME VARCHAR(100) not NULL
);

create table LIVE (
  HOUSE_ID INT not NULL,
  MEMBER_ID INT not NULL
);

create table MEMBER (
  MEMBER_ID INT,
  MEMBER_NAME VARCHAR(100) not NULL
);

create table WORK (
  MEMBER_ID INT not NULL,
  HOUSEWORK_ID INT not NULL,
  STATUS INTEGER not NULL,
  WORK_DATE DATE not NULL
);